"""
Main snakefile with executes all rules in correct order
"""
configfile: "config/config.yaml"

rule all:
    input:
        expand("results/ribo/ribo_profile_{sample}.gff",sample=config["samples"])

include: "rules/trimmomatic.smk"
include: "rules/mapping.smk"
include: "rules/decompiler.smk"
include: "rules/GFF3_annotation.smk"
include: "rules/meta_analysis.smk"
include: "rules/ribo-seq_profile.smk"
