#Configfile
datadir: data/

samples:  ['Eco_Ctrl1', 'Eco_Ctrl2', 'Eco_Exp1', 'Eco_Exp2']
ribo_adapter: RiboSeq_adapter_as

ext:
  raw_reads: .fastq.gz
  genome: .fa
  
threads: 8
  
  
trimmomatic:
  jar: software/Trimmomatic-0.39/trimmomatic-0.39.jar
  phred: -phred33
  minlen: 12
  maxmismatch: 2
  pairend: 30
  minscore: 6
  slidewindow: 4
  minqual: 15